<?php
require __DIR__.'/ui.php';role(['admin','gerente','vendedor','caixa']);$p=db();$products=$p->query("SELECT * FROM products WHERE active=1 ORDER BY name")->fetchAll();$customers=$p->query("SELECT id,name FROM customers ORDER BY name")->fetchAll();$sellers=$p->query("SELECT id,name FROM users WHERE active=1 AND role IN('admin','gerente','vendedor') ORDER BY name")->fetchAll();$coupons=$p->query("SELECT * FROM coupons WHERE active=1")->fetchAll();
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$items=json_decode($_POST['items']??'[]',true);if(!$items){flash('error','Adicione itens.');go('pdv.php');}$p->beginTransaction();try{$sub=0;$cost=0;foreach($items as $i){$s=$p->prepare("SELECT * FROM products WHERE id=?");$s->execute([$i['id']]);$pr=$s->fetch();if(!$pr)throw new RuntimeException('Produto inválido no carrinho.');$q=max(.01,floatval($i['qty']));$avail=available_stock_for_product((int)$pr['id'],$q);if(!$avail['ok'])throw new RuntimeException($avail['message']);$sub+=($pr['price']+floatval($i['customization_value']))*$q;$cost+=$pr['cost']*$q;}$discount=max(0,floatval($_POST['discount']));$maxDiscountPct=(float)setting('max_discount_percent','10');if(!can(['admin','gerente']) && $sub>0 && ($discount/$sub*100)>$maxDiscountPct)throw new RuntimeException('Desconto acima do limite permitido de '.$maxDiscountPct.'%.');$couponCode=trim($_POST['coupon']);if($couponCode){$s=$p->prepare("SELECT * FROM coupons WHERE code=? AND active=1 AND (expiry_date IS NULL OR expiry_date>=date('now'))");$s->execute([$couponCode]);if($c=$s->fetch())$discount+=($c['type']==='percentual'?$sub*$c['value']/100:$c['value']);}$delivery=floatval($_POST['delivery_fee']);$total=max(0,$sub+$delivery-$discount);$number=next_number('PED-','orders');$p->prepare("INSERT INTO orders(number,customer_id,seller_id,occasion,payment_method,subtotal,discount,delivery_fee,total,cost,profit,status,production_stage,art_status,delivery_type,delivery_date,delivery_time,recipient_name,recipient_phone,delivery_address,notes,public_token,priority,production_due_date)VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)")->execute([$number,$_POST['customer_id']?:null,$_POST['seller_id']?:current_user()['id'],$_POST['occasion'],$_POST['payment_method'],$sub,$discount,$delivery,$total,$cost,$total-$cost,'Recebido','Novo',$_POST['has_art']==='1'?'Aguardando arte':'Não se aplica',$_POST['delivery_type'],$_POST['delivery_date']?:null,$_POST['delivery_time']?:null,$_POST['recipient_name'],$_POST['recipient_phone'],$_POST['delivery_address'],$_POST['notes'],bin2hex(random_bytes(24)),$_POST['priority']??'Normal',$_POST['production_due_date']?:($_POST['delivery_date']?:null)]);$oid=(int)$p->lastInsertId();
foreach($items as $i){$s=$p->prepare("SELECT * FROM products WHERE id=?");$s->execute([$i['id']]);$pr=$s->fetch();$q=max(.01,floatval($i['qty']));$p->prepare("INSERT INTO order_items(order_id,product_id,product_name,qty,unit_price,unit_cost,customization,customization_value,personalized_text,details)VALUES(?,?,?,?,?,?,?,?,?,?)")->execute([$oid,$pr['id'],$pr['name'],$q,$pr['price'],$pr['cost'],$i['customization'],$i['customization_value'],$i['text'],$i['details']]);consume_product_stock((int)$pr['id'],$q,'order',$oid);}
if($_POST['delivery_type']==='Entrega local')$p->prepare("INSERT INTO deliveries(order_id,status)VALUES(?,'Pendente')")->execute([$oid]);
$entryPct=max(0,min(100,floatval($_POST['entry_pct'])));$entry=$total*$entryPct/100;$balance=$total-$entry;if($entry>0)$p->prepare("INSERT INTO receivables(order_id,customer_id,description,amount,due_date,status,paid_at)VALUES(?,?,?,?,?,'Recebido',datetime('now','localtime'))")->execute([$oid,$_POST['customer_id']?:null,'Entrada',$entry,date('Y-m-d')]);if($balance>0)$p->prepare("INSERT INTO receivables(order_id,customer_id,description,amount,due_date,status)VALUES(?,?,?,?,?,'Em aberto')")->execute([$oid,$_POST['customer_id']?:null,'Saldo',$balance,$_POST['delivery_date']?:date('Y-m-d')]);
if($_POST['customer_id']){$ratio=max(1,(float)setting('loyalty_spend_per_point','10'));$pts=(int)floor($total/$ratio);$p->prepare("UPDATE customers SET points=points+? WHERE id=?")->execute([$pts,$_POST['customer_id']]);$p->prepare("INSERT INTO loyalty_transactions(customer_id,points,description)VALUES(?,?,?)")->execute([$_POST['customer_id'],$pts,'Pedido '.$number]);}
timeline_event($oid,'created','Pedido criado','Pedido '.$number.' criado no PDV no valor de '.money($total));audit('create','orders',$oid,['number'=>$number,'total'=>$total]);$p->commit();flash('success','Pedido '.$number.' criado.');go('order.php?id='.$oid);}catch(Throwable $e){$p->rollBack();flash('error',$e->getMessage());go('pdv.php');}}
page_head('PDV / Nova encomenda');?>
<form method="post" id="saleForm"><?=csrf_field()?><input type="hidden" name="items" id="itemsJson"><div class="grid g2"><div>
<div class="card"><h2>Dados da venda</h2><div class="grid g3"><div><label>Cliente</label><select name="customer_id"><option value="">Consumidor</option><?php foreach($customers as $c):?><option value="<?=$c['id']?>"><?=e($c['name'])?></option><?php endforeach;?></select></div><div><label>Vendedor</label><select name="seller_id"><?php foreach($sellers as $s):?><option value="<?=$s['id']?>" <?=$s['id']==current_user()['id']?'selected':''?>><?=e($s['name'])?></option><?php endforeach;?></select></div><div><label>Ocasião</label><input name="occasion" placeholder="Aniversário, romântico..."></div><div><label>Pagamento</label><select name="payment_method"><option>Pix</option><option>Dinheiro</option><option>Cartão de débito</option><option>Cartão de crédito</option><option>Transferência</option></select></div><div><label>Entrada %</label><input type="number" name="entry_pct" value="50"></div><div><label>Desconto R$</label><input type="number" step=".01" name="discount" value="0"></div><div><label>Cupom</label><input name="coupon" placeholder="Código"></div><div><label>Prioridade</label><select name="priority"><option>Normal</option><option>Alta</option><option>Urgente</option></select></div><div><label>Prazo interno produção</label><input type="date" name="production_due_date"></div><div><label>Precisa aprovação de arte?</label><select name="has_art"><option value="0">Não</option><option value="1">Sim</option></select></div></div></div>
<div class="card"><h2>Adicionar item</h2><div class="grid g3"><div><label>Produto</label><select id="prod"><?php foreach($products as $x):?><option value="<?=$x['id']?>" data-name="<?=e($x['name'])?>" data-price="<?=$x['price']?>"><?=e($x['name'])?> • <?=money($x['price'])?></option><?php endforeach;?></select></div><div><label>Qtd.</label><input id="qty" type="number" step=".01" value="1"></div><div><label>Personalização</label><input id="cust"></div><div><label>Adicional R$</label><input id="custValue" type="number" step=".01" value="0"></div><div><label>Texto/nome</label><input id="msg"></div></div><label>Detalhes</label><textarea id="details"></textarea><button type="button" class="primary" onclick="addItem()">Adicionar</button></div>
<div class="card"><h2>Entrega</h2><div class="grid g3"><div><label>Tipo</label><select name="delivery_type"><option>Retirada na loja</option><option>Entrega local</option></select></div><div><label>Data</label><input name="delivery_date" type="date"></div><div><label>Hora</label><input name="delivery_time" type="time"></div><div><label>Taxa</label><input name="delivery_fee" id="deliveryFee" type="number" step=".01" value="0"></div><div><label>Destinatário</label><input name="recipient_name"></div><div><label>Telefone</label><input name="recipient_phone"></div></div><label>Endereço</label><textarea name="delivery_address"></textarea><label>Observações</label><textarea name="notes"></textarea></div>
</div><div><div class="card"><h2>Carrinho</h2><div class="table"><table><tr><th>Item</th><th>Qtd.</th><th>Unit.</th><th>Total</th><th></th></tr><tbody id="cart"></tbody></table></div><p class="total" id="cartTotal">R$ 0,00</p><button class="green">Finalizar pedido</button></div></div></div></form>
<script>
let items=[];const br=v=>v.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
function addItem(){let s=document.getElementById('prod'),o=s.options[s.selectedIndex];items.push({id:+o.value,name:o.dataset.name,price:+o.dataset.price,qty:+document.getElementById('qty').value||1,customization:document.getElementById('cust').value,customization_value:+document.getElementById('custValue').value||0,text:document.getElementById('msg').value,details:document.getElementById('details').value});render();}
function removeItem(i){items.splice(i,1);render()}function render(){let t=0;document.getElementById('cart').innerHTML=items.map((x,i)=>{let v=(x.price+x.customization_value)*x.qty;t+=v;return `<tr><td>${x.name}</td><td>${x.qty}</td><td>${br(x.price+x.customization_value)}</td><td>${br(v)}</td><td><button type="button" onclick="removeItem(${i})">X</button></td></tr>`}).join('');document.getElementById('cartTotal').textContent=br(t);document.getElementById('itemsJson').value=JSON.stringify(items)}document.getElementById('saleForm').onsubmit=()=>document.getElementById('itemsJson').value=JSON.stringify(items);
</script><?php page_foot();?>