<?php
require __DIR__.'/config.php';
$token=trim($_GET['token']??'');if($token===''){http_response_code(404);exit('Pedido não encontrado.');}
$s=db()->prepare("SELECT o.*,c.name customer FROM orders o LEFT JOIN customers c ON c.id=o.customer_id WHERE o.public_token=?");$s->execute([$token]);$o=$s->fetch();if(!$o){http_response_code(404);exit('Pedido não encontrado.');}$id=(int)$o['id'];
if($_SERVER['REQUEST_METHOD']==='POST'){csrf_check();$action=$_POST['action']??'';$notes=trim($_POST['notes']??'');if(in_array($action,['Aprovada','Alteração solicitada'],true)){db()->prepare("UPDATE orders SET customer_approval_status=?,customer_approval_notes=?,art_status=? WHERE id=?")->execute([$action,$notes,$action==='Aprovada'?'Aprovada':'Alteração solicitada',$id]);db()->prepare("INSERT INTO artwork_history(order_id,status,notes,user_id)VALUES(?,?,?,NULL)")->execute([$id,$action,$notes]);}elseif($action==='message'&&$notes!==''){db()->prepare("INSERT INTO portal_messages(order_id,sender,message)VALUES(?,'Cliente',?)")->execute([$id,$notes]);}go('portal.php?token='.urlencode($token));}
$s=db()->prepare("SELECT * FROM order_items WHERE order_id=?");$s->execute([$id]);$items=$s->fetchAll();$s=db()->prepare("SELECT * FROM portal_messages WHERE order_id=? ORDER BY id");$s->execute([$id]);$msgs=$s->fetchAll();
?><!doctype html><html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><link rel="stylesheet" href="style.css"><title>Acompanhar pedido</title></head><body><main style="max-width:900px;margin:30px auto;padding:15px"><div class="card"><h1><?=e(setting('store_name','Minha Floricultura'))?></h1><h2>Pedido <?=e($o['number'])?></h2><p>Olá, <b><?=e($o['customer']?:$o['recipient_name'])?></b>.</p><div class="grid g3"><div class="kpi"><span>Status</span><strong><?=e($o['status'])?></strong></div><div class="kpi"><span>Produção</span><strong><?=e($o['production_stage'])?></strong></div><div class="kpi"><span>Arte</span><strong><?=e($o['art_status'])?></strong></div></div><p>Entrega: <?=e($o['delivery_date'])?> <?=e($o['delivery_time'])?></p><p class="total"><?=money($o['total'])?></p></div>
<div class="card"><h2>Itens</h2><?php foreach($items as $i):?><p><b><?=$i['qty']?>x <?=e($i['product_name'])?></b><?php if($i['customization']):?> — <?=e($i['customization'])?><?php endif;?><?php if($i['personalized_text']):?><br><small>Texto: <?=e($i['personalized_text'])?></small><?php endif;?></p><?php endforeach;?></div>
<?php if($o['art_status']!=='Não se aplica' && $o['art_status']!=='Aprovada'):?><div class="card"><h2>Aprovação da arte</h2><form method="post"><?=csrf_field()?><label>Observação</label><textarea name="notes" placeholder="Informe alterações, se necessário"></textarea><div class="actions"><button class="green" name="action" value="Aprovada">Aprovar arte</button><button name="action" value="Alteração solicitada">Solicitar alteração</button></div></form></div><?php endif;?>
<div class="card"><h2>Mensagem para a loja</h2><?php foreach($msgs as $m):?><p><b><?=e($m['sender'])?>:</b> <?=e($m['message'])?> <small><?=e($m['created_at'])?></small></p><?php endforeach;?><form method="post"><?=csrf_field()?><textarea name="notes" placeholder="Escreva sua mensagem"></textarea><button class="primary" name="action" value="message">Enviar</button></form></div></main></body></html>